---
title: "03e_post_scVI_SCEVAN_PerSample_NBAtlas"
author: "Noah Bonine"
date: "`r Sys.Date()`"
output:
    html_document:
        theme: cosmo
        highlight: textmate
        df_print: paged
        toc: true
        toc_depth: 2
params:
    nCores: x
    index1: x
    indexN: x
---

```{r libs}
suppressPackageStartupMessages({
  library(Seurat)
  library(tidyverse)
})

options(bitmapType='cairo')
```
```{r seed}
set.seed(123)
```

```{r extra_libs}
library("SCEVAN", lib.loc = "/data/gent/vo/000/gvo00027/SingleCell10X/Rprojects_NBN/Libraries/R_4.2.1-foss-2022a")
library("yaGST", lib.loc = "/data/gent/vo/000/gvo00027/SingleCell10X/Rprojects_NBN/Libraries/R_4.2.1-foss-2022a")
```

```{r setwd}
setwd("/kyukon/scratch/gent/vo/000/gvo00027/projects/Single_Cell_Neuroblastoma/NBAtlas/03e_post_scVI_SCEVAN_PerSample_NBAtlas")
knitr::opts_knit$set(root.dir = "/kyukon/scratch/gent/vo/000/gvo00027/projects/Single_Cell_Neuroblastoma/NBAtlas/03e_post_scVI_SCEVAN_PerSample_NBAtlas")
```

```{r params}
params

nCores <- params$nCores
index1 <- params$index1
indexN <- params$indexN
```


```{r dirs}
output_dir <- "./"

output_figures <- paste0(output_dir, "Figures/")
output_tables <- paste0(output_dir, "Tables/")
output_Robjects <- paste0(output_dir, "Robjects/")

dir_SignaturePlots <- paste0(output_figures, "/SignaturePlots/")
dir_FeaturePlots <- paste0(output_figures, "/FeaturePlots/")


dir.create(output_dir)
dir.create(output_figures)
dir.create(output_tables)
dir.create(output_Robjects)

dir.create(dir_SignaturePlots)
dir.create(dir_FeaturePlots)
```

```{r extra_params}
step <- "03e_post_scVI_SCEVAN_PerSample_NBAtlas"
project <- "NBAtlas"
```


```{r load_seurat}
seuratObj <- readRDS("/scratch/gent/vo/000/gvo00027/projects/Single_Cell_Neuroblastoma/NBAtlas/03b_post_scVI_R_NBAtlas/Robjects/03b_post_scVI_scVI_covSample_moreEpochs20230322_seuratObj_NormOnly_NBAtlas.rds")
metaData <- read.csv("/scratch/gent/vo/000/gvo00027/projects/Single_Cell_Neuroblastoma/NBAtlas/03c_post_scVI_R_plots/Tables/03c_post_scVI_R_plots_covSample_MetaDataForInferCNV.csv")
```
```{r subset_rbcs}
cells_keep <- rownames(metaData)[!( metaData$annot_NBN_iCNV %in%"RBCs")]

seuratObj$cellname <- Cells(seuratObj)
seuratObj <- subset(seuratObj, subset = cellname %in% cells_keep)

metaData <- metaData[cells_keep,]

ref_cells_all <- rownames(metaData)[!(metaData$annot_NBN_iCNV %in% c("Fibroblast", "NE", "Schwann"))]

seurat_obj_list <- SplitObject(seuratObj, "Sample") #split obj per sample

rm(seuratObj)
gc()
```

```{r run_scevan}
sample_names <- names(seurat_obj_list)

for (i in index1:indexN){
  sam.name <- sample_names[i]
  message(paste0("Starting scevan for sample: ", sam.name)) # to command line
  print(paste0("Starting scevan for sample: ", sam.name)) # to html
  
  rawmat <- GetAssayData(seurat_obj_list[[i]], slot = "counts") # input: raw matrix
  ref_cells <- ref_cells_all[ref_cells_all %in% Cells(seurat_obj_list[[i]])]
  
  print(paste0("Number of ref cells: ", length(ref_cells)))
  print(paste0("Percentage of ref cells: ", length(ref_cells)/length(Cells(seurat_obj_list[[i]]))*100))
  
  if (length(ref_cells) >= 100){
  # run scevan pipeline
  
  results <- pipelineCNA(count_mtx = rawmat, sample = sam.name, norm_cell = ref_cells, SUBCLONES = F, par_cores = nCores)
  saveRDS(results, file = paste0(output_Robjects, step, "_", sam.name, "_results_Robj_", project, ".rds"))
  } else{
  message(paste0("Insufficient reference cells for sample: ", sam.name, " (", length(ref_cells), ")"))
  print(paste0("Insufficient reference cells for sample: ", sam.name, " (", length(ref_cells), ")"))
  }
  rm(rawmat,ref_cells)
  gc()
}
```
