---
title: "RunNMF"
author: "Noah Bonine"
date: "`r Sys.Date()`"
output:
    html_document:
        theme: cosmo
        highlight: textmate
        df_print: paged
        toc: true
        toc_depth: 2
params:
    output_dir: x
    nCores: x
    input_seuratObj : x
    step : x
    i1 : x
    i2: x
---

```{r libs}
suppressPackageStartupMessages({
  library(Seurat)
  library(tidyverse)
  library(scales)
  library(RColorBrewer)
  library(stringr)
  library(NMF)
  library(doParallel)
})
options(bitmapType='cairo')
```

```{r seed}
set.seed(123)
```

```{r dirs}
output_dir <- params$output_dir
output_figures <- paste0(output_dir, "Figures/")
output_tables <- paste0(output_dir, "Tables/")
output_Robjects <- paste0(output_dir, "Robjects/")
dir.create(output_dir)
dir.create(output_figures)
dir.create(output_tables)
dir.create(output_Robjects)
```

```{r params}
params

nCores <- params$nCores
input_seuratObj <- params$input_seuratObj
step <- params$step
i1 <- params$i1
i2 <- params$i2
```


# Load seuratObj
```{r load_seurat}
#lightweight
seuratObj <- readRDS(input_seuratObj)
```

# NMFs
Gavish 2023 : https://github.com/tiroshlab/3ca/tree/main/ITH_hallmarks & https://github.com/gabrielakinker/CCLE_heterogeneity

Run NMF using ranks 4-9 on the top 7000 genes in each sample
```{r runNMF, message = F}
samples <- levels(as.factor(seuratObj$Sample))

Genes_nmf_w_basis <- list()
for(i in i1:i2){
  Expression_matrix <- subset(seuratObj, subset = Sample == samples[i])
  if (length(Cells(Expression_matrix)) >= 10){ # select min 10 cells (as authors do)
    Expression_matrix <- NormalizeData(Expression_matrix, normalization.method = "LogNormalize")
    Expression_matrix <- FindVariableFeatures(Expression_matrix, nfeatures = 7000) # determine top 7000 genes
    Expression_matrix <- ScaleData(Expression_matrix) # use centered matrix
    Expression_matrix <- Expression_matrix@assays$RNA@scale.data 
    Expression_matrix[Expression_matrix < 0 ] <- 0
    message(paste0("Started running NMF for ", samples[i], " ..."))
    NMFs_per_sample <- nmf(x = Expression_matrix, rank = 4:9, method="snmf/r", nrun = 10, seed = 123, .options = paste0('v+p', nCores))
    message(paste0("Saving NMF results for ", samples[i], " ..."))
    saveRDS(NMFs_per_sample, file = paste0(output_Robjects, step, "_NMF_",samples[i], '_rank4_9_nrun10.RDS')) # save with: '_rank4_9_nrun10.RDS'
    
    rm(NMFs_per_sample, Expression_matrix)
    gc()
  } else{
    message_parallel(paste0("Insufficient malignant cells for sample: ", samples[i], ", not running NMF."))
    print(paste0("Insufficient malignant cells for sample: ", samples[i], ", not running NMF."))
  }
}
```