---
title: "09c_post_scVI_MalignantZoom_R_plots"
author: "Noah Bonine"
date: '`r Sys.Date()`'
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(tidyverse)
  library(scales)
  library(RColorBrewer)
  library(svglite)
  library(arrow)
  library(stringr)
  library(fgsea)
  library(ggpointdensity)
  library(RColorBrewer)
  library(UCell)
  library(escape)
  library(dittoSeq)
})

options(bitmapType='cairo')
```

```{r}
set.seed(123)
```

```{r}
setwd("/scratch/gent/vo/000/gvo00027/projects/Single_Cell_Neuroblastoma/NBAtlas")
```
```{r}
output_dir <- "09c_post_scVI_MalignantZoom_R_plots/"
output_figures <- paste0(output_dir, "Figures/")
output_tables <- paste0(output_dir, "Tables/")
output_Robjects <- paste0(output_dir, "Robjects/")
dir_SignaturePlots <- paste0(output_figures, "/SignaturePlots/")
dir_FeaturePlots <- paste0(output_figures, "/FeaturePlots/")
dir.create(output_dir)
dir.create(output_figures)
dir.create(output_tables)
dir.create(output_Robjects)
dir.create(dir_SignaturePlots)
dir.create(dir_FeaturePlots)
```

```{r}
reduction_to_plot <- "scvi_umap"
step <- "09c_post_scVI_MalignantZoom_R"
project <- "NBAtlas"
```

```{r}
Sample_colors <- readRDS("03c_post_scVI_R_plots/Robjects/UMAP_Sample_colors_v1.rds")
```

# Load seuratObj
```{r}
#lightweight
seuratObj <- readRDS("09b_post_scVI_MalignantZoom_R_import_NBAtlas/Robjects/09b_post_scVI_MalignantZoom_R_import_MalignantZoom_scVI_covSample_2layers_seuratObj_NormOnly_NBAtlas.rds")
```

```{r}
# reload annot
MetaData <- readRDS("09c_post_scVI_MalignantZoom_R_plots/Robjects/09c_post_scVI_MalignantZoom_R_SeuratMetadata_AnnotNBN_NBAtlas.rds")

seuratObj$clusters <- MetaData$clusters
seuratObj$cluster_nr <- MetaData$cluster_nr

scvi_umap <- Embeddings(seuratObj, reduction = "scvi_umap")
seuratObj$scvi_umap1 <- scvi_umap[,1]
seuratObj$scvi_umap2 <- scvi_umap[,2]
```

# Plots
```{r}
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

seuratObj <- CellCycleScoring(seuratObj, s.features = s.genes, g2m.features = g2m.genes)

# plot
DimPlot(seuratObj, group.by = "Phase", reduction = reduction_to_plot, raster = F, shuffle = T)
ggsave(filename = paste0(output_figures, step, "_UMAP_CellCyclePhase_NoRaster_", project, ".png"), width = 9, height = 7)
```


```{r}
FeaturePlot(seuratObj, features = "MYCN", min.cutoff = "q2", max.cutoff = "q98", raster = F, order = T) + scale_colour_gradientn(colors = c("gray","blue","black"))
ggsave(filename = paste0(step, "_UMAP_MYCN_BlueBlack",  project, ".png"), path = dir_FeaturePlots, width = 9, height = 7)
```

# Gene sets

## FGSEA
### Reactome
```{r}
gs_collection_name <- "Reactome"
reactome_gs <- msigdbr::msigdbr(species = "Homo sapiens", category = "C2", subcategory = "REACTOME") 
updated_gene_symbol <- update_geneSet_NBAtlas(reactome_gs$gene_symbol)# update genes
reactome_gs$gene_symbol <- updated_gene_symbol
term2gene <- reactome_gs %>% dplyr::select(gs_name, gene_symbol)
gene_set_list <- term2gene %>% group_by(gs_name) %>% summarize(all.genes = list(unique(gene_symbol))) %>% deframe() #convert to list
```
```{r}
cluster_levels <- levels(as.factor(seuratObj$cluster_nr))
fgseaRes_results <- list()
fgseaRes_results_sign <- list()
for (c in cluster_levels){
  ranks <- findmarkers_results[[c]]$score #based on score
  names(ranks) <- rownames(findmarkers_results[[c]])
  
  fgseaRes <- fgsea(pathways = gene_set_list, stats = ranks,
                    minSize=10,maxSize=500,scoreType="pos",nproc=1)
  fgseaRes$minlog10padj <- -log10(fgseaRes$pval)
  fgseaRes$pathway <- gsub(pattern = "REACTOME_", x = fgseaRes$pathway, replacement = "")
  n_sign_genes <- sum(fgseaRes$padj <= 0.1)
  if (n_sign_genes > 30 ){n_sign_genes = 30}
  if (n_sign_genes > 0 ){
    fgseaRes_ordered <- fgseaRes %>% filter(fgseaRes$padj <= 0.1) %>% arrange(desc(NES)) %>% dplyr::slice(1:n_sign_genes) # take first 30 sign
    ggplot(fgseaRes_ordered, aes(x = reorder(pathway,NES), y = NES, fill = minlog10padj)) + geom_col() + coord_flip() + scale_fill_viridis() + xlab("") + ggtitle(c) + theme_point # dotplot
    ggsave(filename = paste0(output_figures, step, "_fgsea_FDR-0p1_", gs_collection_name, "_", c, "_", project, ".svg" ), width = 10, height = 5)
    fgseaRes_results[[c]] <- fgseaRes_ordered
  fgseaRes_results_sign[[c]] <- fgseaRes_ordered[fgseaRes_ordered$padj < 0.1,]
  } else {
    print(paste0("No FDR < 0.1 gene sets found for ", c))
  }
}
saveRDS(fgseaRes_results, file = paste0(output_Robjects, step, "_fgsea_FDR-0p1_", gs_collection_name, "_", project, ".rds"))
openxlsx::write.xlsx(fgseaRes_results_sign, file = paste0(output_tables, step, "_fgsea_FDR-0p1_", gs_collection_name, "_", project, ".xlsx"), overwrite = T)
rm(gs_collection_name, gene_set_list)
```

### ChEA2022
```{r}
ChEA2022_gmt <- GSA.read.gmt("/data/gent/vo/000/gvo00027/vsc44341/R_HelperFunctions_NB/ChEA_2022_geneSetLibrary.gmt") # from https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=ChEA_2022
ChEA2022_list <- as.list(ChEA2022_gmt$genesets)
names(ChEA2022_list) <- ChEA2022_gmt$geneset.names 
geneset_collection <- ChEA2022_list
gs_collection_name <- "ChEA2022"
set_name_vector <- character()
gene_id_vector <- character()
for (set_name in names(geneset_collection)) {
  gene_ids <- unlist(geneset_collection[[set_name]])
  gene_ids <- gene_ids[nchar(gene_ids) >0]# remove empty elements
  set_name_vector <- c(set_name_vector, rep(set_name, length(gene_ids)))
  gene_id_vector <- c(gene_id_vector, gene_ids)
}
geneset_collection_df <- data.frame(gs_name = set_name_vector, gene_symbol = gene_id_vector, stringsAsFactors = FALSE)
updated_gene_symbol <- update_geneSet_NBAtlas(geneset_collection_df$gene_symbol)
any(is.na(updated_gene_symbol))
geneset_collection_df$gene_symbol <- updated_gene_symbol
term2gene <- geneset_collection_df %>% dplyr::select(gs_name, gene_symbol)
gene_set_list <- term2gene %>% group_by(gs_name) %>% summarize(all.genes = list(unique(gene_symbol))) %>% deframe() #convert to list
```
```{r}
cluster_levels <- levels(as.factor(seuratObj$cluster_nr))
fgseaRes_results <- list()
fgseaRes_results_sign <- list()
for (c in cluster_levels){
  ranks <- findmarkers_results[[c]]$score #based on score
  names(ranks) <- rownames(findmarkers_results[[c]])
  
  fgseaRes <- fgsea(pathways = gene_set_list, stats = ranks,
                    minSize=10, maxSize=500, scoreType="pos", nproc=1)
  fgseaRes$minlog10padj <- -log10(fgseaRes$pval)
  fgseaRes$pathway <- gsub(pattern = "REACTOME_", x = fgseaRes$pathway, replacement = "")
  n_sign_genes <- sum(fgseaRes$padj <= 0.1)
  if (n_sign_genes > 30 ){n_sign_genes = 30}
  if (n_sign_genes > 0 ){
    fgseaRes_ordered <- fgseaRes %>% filter(fgseaRes$padj <= 0.1) %>% arrange(desc(NES)) %>% dplyr::slice(1:n_sign_genes) # take first 30 sign
    ggplot(fgseaRes_ordered, aes(x = reorder(pathway,NES), y = NES, fill = minlog10padj)) + geom_col() + coord_flip() + scale_fill_viridis() + xlab("") + ggtitle(c) + theme_point
    ggsave(filename = paste0(output_figures, step, "_fgsea_FDR-0p1_", gs_collection_name, "_", c, "_", project, ".svg" ), width = 10, height = 5)
    fgseaRes_results[[c]] <- fgseaRes_ordered
  fgseaRes_results_sign[[c]] <- fgseaRes_ordered[fgseaRes_ordered$padj < 0.1,]
  } else {
    print(paste0("No FDR < 0.1 gene sets found for ", c))
  }
}
saveRDS(fgseaRes_results, file = paste0(output_Robjects, step, "_fgsea_FDR-0p1_", gs_collection_name, "_", project, ".rds"))
openxlsx::write.xlsx(fgseaRes_results_sign, file = paste0(output_tables, step, "_fgsea_FDR-0p1_", gs_collection_name, "_", project, ".xlsx"), overwrite = T)
rm(gs_collection_name, gene_set_list)
```

## Signatures

```{r}
# reload
ranks <- readRDS("09c_post_scVI_MalignantZoom_R_CalcUCellRanks_NBAtlas/Robjects/09c_post_scVI_MalignantZoom_R_UCellPreCompRanks_NBAtlas.rds") #CalcUCellRanks_NBAtlas script 
```

## Gavish 2023
```{r}
Gavish2023_malignant_metaprograms <- openxlsx::read.xlsx("/data/gent/vo/000/gvo00027/vsc44341/R_HelperFunctions_NB/Gavish2023_meta_programs_2023-07-13.xlsx", sheet = "Malignant")
```

```{r}
#make list obj (required for enrichIt)
Gavish2023_malignant_metaprograms_list <- as.list(Gavish2023_malignant_metaprograms)

enrichIt_scores_metaprograms <- enrichIt(obj = seuratObj, 
                      gene.sets = Gavish2023_malignant_metaprograms, 
                      groups = 1000, #groups of cells to process
                      cores = 1,
                      method = "UCell",
                      precalc.rank = ranks,
                      force.gc = T) #remove gene sets with <5 genes
saveRDS(enrichIt_scores_metaprograms, file = paste0(output_Robjects, step, "_enrichIT_UCell_Gavish2023MalignantMetaPrograms.rds"))
```

```{r}
enrichIt_scores_metaprograms <- readRDS(paste0(output_Robjects, step, "_enrichIT_UCell_Gavish2023MalignantMetaPrograms.rds"))
seuratObj <- AddMetaData(seuratObj, enrichIt_scores_metaprograms)
```

#### Signature plots

```{r}
# Stress signatures
FeaturePlot(seuratObj, features = "Stress", raster = F, max.cutoff = 'q98', min.cutoff = 0, order = T) + blue_red_spectral_color_scale11
ggsave(filename = paste0(step, "_UMAP_", "Gavish2023_StressMetaprogram_BlueYellowRed_", "_UCell_", project, ".png"), path = dir_SignaturePlots, width = 9, height = 7)

FeaturePlot(seuratObj, features = "Stress..in.vitro.", raster = F, max.cutoff = 'q98', min.cutoff = 0, order = T) + blue_red_spectral_color_scale11
ggsave(filename = paste0(step, "_UMAP_", "Gavish2023_InVitroStressMetaprogram_BlueYellowRed_", "_UCell_", project, ".png"), path = dir_SignaturePlots, width = 9, height = 7)
```

#### Dissociation stress
```{r}
dissociation_signatures <- list(vandenBrink2017_diss_sign = vandenBrink2017_diss_sign, OFlanagan2019_diss_sign = OFlanagan2019_diss_sign, hsp_genes = hsp_genes, RPGs = RPGs)
```

```{r}
enrichIt_scores_dissociation_signatures <- enrichIt(obj = seuratObj, 
                      gene.sets = dissociation_signatures, 
                      groups = 2000, #groups of cells to process
                      cores = 1,
                      method = "UCell",
                      precalc.rank = ranks,
                      force.gc = T) #remove gene sets with <5 genes
saveRDS(enrichIt_scores_dissociation_signatures, file = paste0(output_Robjects, step, "_enrichIT_UCell_DissociationSignatures_NBAtlas.rds"))
```
```{r}
enrichIt_scores_dissociation_signatures <- readRDS(paste0(output_Robjects, step, "_enrichIT_UCell_DissociationSignatures_NBAtlas.rds"))
seuratObj <- AddMetaData(seuratObj, enrichIt_scores_dissociation_signatures)
```

```{r}
FeaturePlot(seuratObj, features = "vandenBrink2017_diss_sign", raster = F, max.cutoff = 'q98', min.cutoff = 0, order = T) + blue_red_spectral_color_scale11
ggsave(filename = paste0(step, "_UMAP_", "vandenBrink2017_diss_sign_BlueYellowRed", "_UCell_", project, ".png"), path = dir_SignaturePlots, width = 9, height = 7)

FeaturePlot(seuratObj, features = "OFlanagan2019_diss_sign", raster = F, max.cutoff = 'q98', min.cutoff = 0, order = T) + blue_red_spectral_color_scale11
ggsave(filename = paste0(step, "_UMAP_", "OFlanagan2019_diss_sign_BlueYellowRed", "_UCell_", project, ".png"), path = dir_SignaturePlots, width = 9, height = 7)
```

```{r}
FeaturePlot(seuratObj, features = "hsp_genes", raster = F, max.cutoff = 'q98', min.cutoff = 0, order = T) + blue_red_spectral_color_scale11
ggsave(filename = paste0(step, "_UMAP_", "HPs_BlueYellowRed", "_UCell_", project, ".png"), path = dir_SignaturePlots, width = 9, height = 7)
```

```{r}
# Yuan intermediate state expr
FeaturePlot(seuratObj, features = c("Yuan2020_intermed"), raster = F, max.cutoff = "q98", min.cutoff = 0, order = T) + blue_red_spectral_color_scale11
ggsave(filename = paste0(step, "_UMAP_", "YuanIntermed_BlueYellowRed_", "_UCell_", project, ".png"), path = dir_SignaturePlots, width = 9, height = 7)
```

# Patient metadata
```{r}
MetaData <- readRDS("03c_post_scVI_R_plots/Robjects/03c_post_scVI_R_MetaData_PatientMetaData.rds")

cellnames_intersect <- rownames(MetaData)[ rownames(MetaData) %in% Cells(seuratObj)]

seuratObj$Platform <- "not assigned"
seuratObj@meta.data[cellnames_intersect,]["Platform"] <- MetaData[cellnames_intersect,]["Platform"]

seuratObj$INSS_stage <- "not assigned" #initialize
seuratObj@meta.data[cellnames_intersect,]["INSS_stage"] <- MetaData[cellnames_intersect,]["INSS_stage"]

seuratObj$Timepoint <- "not assigned" #initialize
seuratObj@meta.data[cellnames_intersect,]["Timepoint"] <- MetaData[cellnames_intersect,]["Timepoint"]

seuratObj$Risk_group <- "not assigned" #initialize
seuratObj@meta.data[cellnames_intersect,]["Risk_group"] <- MetaData[cellnames_intersect,]["Risk_group"]

seuratObj$MYCN_amplification <- "not assigned" #initialize
seuratObj@meta.data[cellnames_intersect,]["MYCN_amplification"] <- MetaData[cellnames_intersect,]["MYCN_amplification"]

seuratObj$Simplified_Risk <- "not assigned" #initialize
seuratObj@meta.data[cellnames_intersect,]["Simplified_Risk"] <- MetaData[cellnames_intersect,]["Simplified_Risk"]
```

```{r}
timepoint_colors <- hue_pal()(length(levels(as.factor(seuratObj$Timepoint))))
timepoint_colors[length(timepoint_colors)] <- "gray"

mycn_colors <- hue_pal()(length(levels(as.factor(seuratObj$MYCN_amplification))))

simplified_risk_colors <- hue_pal()(length(levels(as.factor(seuratObj$Simplified_Risk))))

INSS_colors <- hue_pal()(length(levels(as.factor(seuratObj$INSS_stage))))
INSS_colors[length(INSS_colors)] <- "gray"
```

```{r}
DimPlot(seuratObj, reduction = reduction_to_plot,  group.by = "Timepoint", cols = timepoint_colors)
ggsave(filename = paste0(output_figures, step, "_UMAP_Timepoint_NBAtlas.png"), width = 10, height = 7)

DimPlot(seuratObj, reduction = reduction_to_plot,  group.by = "Timepoint", shuffle = T, raster = F, cols = timepoint_colors)
ggsave(filename = paste0(output_figures, step, "_UMAP_Timepoint_HD_NBAtlas.png"), width = 15, height = 12)

DimPlot(seuratObj, reduction = reduction_to_plot,  group.by = "INSS_stage", cols = INSS_colors)
ggsave(filename = paste0(output_figures, step, "_UMAP_INSS_stage_NBAtlas.png"), width = 9, height = 7)

DimPlot(seuratObj, reduction = reduction_to_plot,  group.by = "INSS_stage", cols = INSS_colors, shuffle = T, raster = F)
ggsave(filename = paste0(output_figures, step, "_UMAP_INSS_stage_HD_NBAtlas.png"), width = 15, height = 12)

seuratObj$MYCN_amplification[seuratObj$Sample == "Verhoeven2022_NB37"] <- "Amplified" #Correction
DimPlot(seuratObj, reduction = reduction_to_plot,  group.by = "MYCN_amplification", cols = mycn_colors)
ggsave(filename = paste0(output_figures, step, "_UMAP_MYCNamplification_v2_NBAtlas.png"), width = 9, height = 7)

DimPlot(seuratObj, reduction = reduction_to_plot,  group.by = "MYCN_amplification", cols = mycn_colors , shuffle = T, raster = F) 
ggsave(filename = paste0(output_figures, step, "_UMAP_MYCNamplification_HD_v2_NBAtlas.png"), width = 15, height = 12)

DimPlot(seuratObj, reduction = reduction_to_plot,  group.by = "Simplified_Risk", cols = simplified_risk_colors)
ggsave(filename = paste0(output_figures, step, "_UMAP_SimplifiedRisk_NBAtlas.png"), width = 9, height = 7)

DimPlot(seuratObj, reduction = reduction_to_plot,  group.by = "Simplified_Risk", cols = simplified_risk_colors, shuffle = T, raster = F)
ggsave(filename = paste0(output_figures, step, "_UMAP_SimplifiedRisk_HD_NBAtlas.png"), width = 15, height = 12)
```
```{r}
# ggpoint densitiy plots
centers <- seuratObj@meta.data %>% filter(Simplified_Risk == "High") %>% dplyr::group_by(cluster_nr) %>% summarize(x = median(x = scvi_umap1), y = median(x = scvi_umap2))

## Risk with annot
ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$Simplified_Risk == "High",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Reds")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_SimplifiedRisk_HR_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$Simplified_Risk == "Low",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Greens")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_SimplifiedRisk_LR_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

## MYCN with annot
ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$MYCN_amplification == "Amplified",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Reds")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_MYCN-Amplified_v2_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$MYCN_amplification == "Non-amplified",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Greens")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_MYCN-non-Amplified_v2_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

# INSS
seuratObj$INSS_stage[seuratObj$INSS_stage == "Localized"] <- "unknown" 
ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$INSS_stage == "1",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Greens")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_INSS1_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$INSS_stage == "2A",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Greens")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_INSS2A_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$INSS_stage == "2B",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Greens")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_INSS2B_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$INSS_stage == "3",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Reds")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_INSS3_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$INSS_stage == "4",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Reds")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_INSS4_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$INSS_stage == "4S",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Greens")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_INSS4S_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

#Timepoint
ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$Timepoint == "pre-treatment",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Greens")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_Timepoint_Pretreatment_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$Timepoint == "post-treatment",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Greens")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_Timepoint_Posttreatment_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)

ggplot() + geom_point(data = seuratObj@meta.data, aes(x = scvi_umap1, y = scvi_umap2), color = "gray90") + #gray background
  geom_pointdensity(data = seuratObj@meta.data[seuratObj$Timepoint == "relapse",], aes(x = scvi_umap1, y = scvi_umap2)) + scale_color_gradientn(colors = RColorBrewer::brewer.pal(9, "Greens")) + theme_point + 
  geom_text(data = centers, aes(x = x, y = y, label = cluster_nr), color='black', fontface='bold', size=4) # add annotation
ggsave(filename = paste0(output_figures, step, "_UMAP_Dens_Timepoint_Relapse_Labeled_NBAtlas.png"), width = 9, height = 7, dpi = 500)
```

## Annot
```{r}
# Rename
seuratObj$clusters[seuratObj$cluster_nr == "c0"] <- "Differentiation I"
seuratObj$clusters[seuratObj$cluster_nr == "c3"] <- "Differentiation II"
seuratObj$clusters[seuratObj$cluster_nr == "c1"] <- "Translation"
seuratObj$clusters[seuratObj$cluster_nr == "c2"] <- "Cycling-S"
seuratObj$clusters[seuratObj$cluster_nr == "c4"] <- "Cycling-G2M"
seuratObj$clusters[seuratObj$cluster_nr == "c5"] <- "Low quality"
seuratObj$clusters[seuratObj$cluster_nr == "c6"] <- "Stress"
seuratObj$clusters[seuratObj$cluster_nr == "c7"] <- "MYCN" #
```

```{r}
table(seuratObj$clusters)
```

```{r}
DimPlot(seuratObj, group.by = "clusters", raster = F)
ggsave(paste0(output_figures, step, "_UMAP_AnnotNBN_", project, ".png"), width = 9, height = 7)

DimPlot(seuratObj, group.by = "clusters", label = T, raster = F)
ggsave(paste0(output_figures, step, "_UMAP_AnnotNBN_Labeled", project, ".png"), width = 9, height = 7)

DimPlot(seuratObj, group.by = "cluster_nr", raster = F)
ggsave(paste0(output_figures, step, "_UMAP_AnnotNBN_ClusterNr", project, ".png"), width = 9, height = 7, dpi = 500)
```

```{r}
# Dotplot annotation
dotplot_genes <- c("NTRK1","CD9","STMN4", #c0. Differentiation I
                    "NPM1","RPS15A","RPS7", #c1. Translation
                   "E2F1", "TYMS", "RRM2", #c2. Cycling-S 
                   "GRID2", "DGKB", "SST", #c3. Differentiation II
                    "MKI67", "TOP2A", "UBE2C", #c4. Cycling-G2M                       
                    #c.5 Low quality: low quality (MT markers)
                    "NDUFA4L2", "COX4I2", "DDIT4", #c6. Stress 
                    "MYCN", "NEUROD1", "EZH2" #c7. MYCN
                    ) 
table(seuratObj$clusters, useNA = "ifany")

seuratObj$clusters_f <- factor(as.character(seuratObj$cluster_nr), levels = rev(levels(as.factor(seuratObj$cluster_nr))))

DotPlot(seuratObj, group.by = "clusters_f", features = dotplot_genes) + blue_red_color_scaleg2 & RotatedAxis()
ggsave(paste0(output_figures, step, "_DotPlot_AnnotNBN_AnnotationMarkers", project, ".svg"), width = 9, height = 5)
```


```{r}
saveRDS(seuratObj@meta.data, file = paste0(output_Robjects, step, "_SeuratMetadata_AnnotNBN_NBAtlas.rds"))
```

```{r}
# reload
MetaData <- readRDS("09c_post_scVI_MalignantZoom_R_plots/Robjects/09c_post_scVI_MalignantZoom_R_SeuratMetadata_AnnotNBN_NBAtlas.rds")

seuratObj$clusters <- MetaData$clusters
seuratObj$cluster_nr <- MetaData$cluster_nr
```

## Barplots
```{r}
# barplot sc vs sn cluster composition
seuratObj@meta.data %>% ggplot() + geom_bar(aes(x = Assay, fill = cluster_nr), position = "fill") + theme_bar_straight + ylab("Clusters (%)")
ggsave(paste0(output_figures, step, "_BarplotStacked_Assay_vs_ClusterAnnot_", project, ".svg"), width = 4, height = 9)

# barplot HR vs LR cluster composition
seuratObj@meta.data %>% ggplot() + geom_bar(aes(x = Simplified_Risk, fill = cluster_nr), position = "fill") + theme_bar_straight + ylab("Clusters (%)")
ggsave(paste0(output_figures, step, "_BarplotStacked_Risk_vs_ClusterAnnot_", project, ".svg"), width = 6, height = 9)

seuratObj@meta.data %>% ggplot() + geom_bar(aes(x = Simplified_Risk, fill = cluster_nr), position = "fill") + facet_grid(~Assay) + theme_bar_straight + ylab("Clusters (%)")
ggsave(paste0(output_figures, step, "_BarplotStacked_Risk_vs_ClusterAnnot_FacetAssay_", project, ".svg"), width = 10, height = 9)
```

```{r}
# Patients per patient
seuratObj@meta.data %>% ggplot() + geom_bar(aes(x = cluster_nr, fill = Sample), position = "fill") + theme_bar_straight + ylab("Relative abundance") + scale_fill_manual(values = Sample_colors) & NoLegend()
ggsave(filename = paste0(step, "_BarPlot_Patients_Per_Cluster_", project, ".pdf"), path = output_figures, width = 7, height = 7)

# Clusters per patient
seuratObj@meta.data %>% ggplot() + geom_bar(aes(x = Sample, fill = cluster_nr), position = "fill") + theme_bar_straight + ylab("Relative abundance") & RotatedAxis()
ggsave(filename = paste0(step, "_BarPlot_Clusters_Per_Patient_", project, ".pdf"), path = output_figures, width = 12, height = 7)
```